### ISSUE TITLE
CI: Check that generated bindings are equal to committed version

### ISSUE THREAD

**Issue by matthiasgeihs** [hyperledger-labs/perun-eth-backend#23]
Updated to 0.8.15. No, we do not check that the generated bindings are equal atm.

_Originally posted by @cryptphil in https://github.com/hyperledger-labs/perun-eth-backend/pull/19#discussion_r923475161_

**Comment by cryptphil** [comment]
Is this issue still open? Because of #33. @matthiasgeihs

**Comment by matthiasgeihs** [comment]
Good point.
